version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd frontend
      - yarn install
  build:
    commands:
      - echo Build iniciado on 'date'
      - yarn vite build
artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/dist'
